#YAML
#YAML(YAML Ain't Markup Language)은 사람이 읽기 좋은 데이터 구조를 목표로 한다. 확장자는 yaml , yml 이다. 주로 yml 을 사용한다.
#YML은 내부 분리를 ---

#주의
#pplication.properties , application.yml 을 같이 사용하면 application.properties 가 우선권을 가진다.
#이것을 둘이 함께 사용하는 것은 일관성이 없으므로 권장하지 않는다.
my:
  datasource:
    url: local.db.com
    username : local_user
    password : local_pw
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL, CACHE
---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username : dev_user
    password : dev_pw
    etc:
      max-connection: 10
      timeout: 60s
      options: DEV, CACHE

---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username : prod_user
    password : prod_pw
    etc:
      max-connection: 50
      timeout: 10s
      options: PROD, CACHE